apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  namespace: edu-admiring-carson
  labels:
    app: django-app
data:
  DEBUG: 'True'
  ALLOWED_HOSTS: 'edu-admiring-carson.sirius-k8s.dvmn.org'
  
