apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  labels:
    app: django-app
data:
  DEBUG: 'True'
  POSTGRES_DB_URL: 'postgres://test_k8s:OwOtBep9Frut@db192.168.99.2:5432/test_k8s'
  SECRET_KEY: 'dsndnsdnsdndsamdsmdlamdamsdl'
